print("=== Mini Project Proposal Generator ===\n")
title = input("Enter Project Title: ")
problem = input("Enter Problem Statement: ")
dataset = input("Enter Dataset Description: ")
algorithm = input("Enter Algorithm / Approach: ")
output = input("Enter Expected Output: ")
print("\n=== Generated Proposal ===\n")
print("Title:")
print(title)
print("\nProblem Statement:")
print(problem)
print("\nDataset:")
print(dataset)
print("\nAlgorithm / Approach:")
print(algorithm)
print("\nExpected Output:")
print(output)
print("\n--- Proposal Ready ---")